### ISSUE TITLE
Some official annoncuments are missing

### ISSUE THREAD

**Issue by sveniu** [vladholubiev/awsnews.info#1]
There seems to be several official announcements missing, even with the noise filter turned off.

For Nov 17th, https://awsnews.info/ has two announcements while https://aws.amazon.com/new/ has 14. The same seems to be the case for earlier dates.

Is this a known issue?

**Comment by vladholubiev** [comment]
Yes, I will be assessing this issue this weekend. Thanks for spotting.

**Comment by vladholubiev** [comment]
Fixed: https://github.com/vladholubiev/awsnews.info-api/commit/28c41c5478abe2e1e2b73b61e470da630d377d4e
